
version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=api_jwt
    depends_on: []
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    x-deploy:
      watch:
        paths:
          - .
        extensions:
          - ts
          - js
          - json
volumes:
  db_data:
