
version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "4001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=nest_user
      - DATABASE_PASSWORD=nest_password
      - DATABASE_NAME=nest_database
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start

  database:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
