
version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    depends_on: []
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    x-deploy:
      watch:
        paths:
          - .
        extensions:
          - ts
          - js
          - json
volumes:
  db_data:
